### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by chocolate012** [NodeBB/nodebb-plugin-emoji#44]
Having this issue lately (I think since upgraded to 1.16.1),
Running;
```
  version:  1.16.2
  Node ver: v10.17.0
  git hash: 023e4cfcee208a0bae121a6e343a8c53009fd090
  database: mongo
        version: 4.0.13
        engine:  wiredTiger
```
The Plugin is not working at all, when opening the composer you get an error,
```
ERROR
Failed to load emoji metadata
```
Here is the log output I get when starting NodeBB;
```
error: [plugins] Error executing 'static:app.load' in plugin 'nodebb-plugin-emoji'
error: TypeError: Object.fromEntries is not a function
    at Object.getAll (/var/www/nodebb/node_modules/nodebb-plugin-emoji/build/lib/customizations.js:13:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error: [emoji] Failed to retrieve data for parse ENOENT: no such file or directory, open '/var/www/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json' {"errno":-2,"code":"ENOENT","syscall":"open","path":"/var/www/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json","stack":"Error: ENOENT: no such file or directory, open '/var/www/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json'"}
```

**Comment by pitaj** [comment]
You need to update your Node version. I suggest Node 14.

**Comment by sweetppro** [comment]
I am also having this issue with v3.5.1
NodeBB v1.16.2
Node.js v14.16.1

**Comment by pitaj** [comment]
Are you sure NodeBB is running under Node 14? `Object.fromEntries` should be available is that's the case.

**Comment by julianlam** [comment]
This is most likely an issue with multiple node executables installed on the same system

**Comment by sweetppro** [comment]
It seems my instance may actually be running node 12.6.3....
😕
