### ISSUE TITLE
warn: [plugins] Callback timed out, hook 'static:app.load' in plugin 'nodebb-plugin-emoji'

### ISSUE THREAD

**Issue by NormandoHall** [NodeBB/nodebb-plugin-emoji#36]
After start nodebb, get this warning

NodeBB: 1.4.1
nodebb-plugin-emoji: 3.3.0

**Comment by pitaj** [comment]
NodeBB v1.4.1 is very old. Did you mean v1.**14**.1?

**Comment by NormandoHall** [comment]
> NodeBB v1.4.1 is very old. Did you mean v1.**14**.1?

Yes, so sorry, 1.14.1. And now the same with updated nodeBB to 1.14.2

**Comment by pitaj** [comment]
Any other issues you're encountering, or does the emoji plugin work fine? Does this happen on every startup? I'd guess that on your system (maybe a little slower than most) the emoji startup code takes long enough to trigger that warning, but still completes successfully.

**Comment by NormandoHall** [comment]
Yes @pitaj, plugin seems work fine. And yes, on every startup, but only after I update nodeBB to 1.14.1.
I opened this issue only for your information. Thanks!

**Comment by chocolate012** [comment]
Having the same issue
```
./nodebb inf
  version:  1.16.2
  Node ver: v10.17.0
  git hash: 023e4cfcee208a0bae121a6e343a8c53009fd090
  database: mongo
        version: 4.0.13
        engine:  wiredTiger
```
Plus the Plugin is not working at all
here is the log output I get
```
error: [plugins] Error executing 'static:app.load' in plugin 'nodebb-plugin-emoji'
error: TypeError: Object.fromEntries is not a function
    at Object.getAll (/var/www/nodebb/node_modules/nodebb-plugin-emoji/build/lib/customizations.js:13:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error: [emoji] Failed to retrieve data for parse ENOENT: no such file or directory, open '/var/www/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json' {"errno":-2,"code":"ENOENT","syscall":"open","path":"/var/www/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json","stack":"Error: ENOENT: no such file or directory, open '/var/www/nodebb/node_modules/nodebb-plugin-emoji/build/emoji/table.json'"}
```

**Comment by barisusakli** [comment]
I increased the static:hook timeout to 10secs form 5secs hopefully its fine now. The buildAssets call in that function might take a while to complete and cause that timeout
